#!/usr/bin/env bash

# Exit with error if it doesn't recieve a script name on the commandline
if [ -z "$1" ]; then
  echo \!\!\! - No script name provided
  exit 255
fi

# Set up our directories, I suggest $HOME/.gt for this script and $HOME/.gt/scripts for the others
gt_dir=$HOME/.gt
gt_script_dir=$gt_dir/scripts

function find_script { find $gt_script_dir -name "$1.*" 2> /dev/null | head -1; }
gt_script=$(find_script $1)

# If the script is found, then run it
if [ -e "$gt_script" ]; then

  error_log=$gt_dir/logs/$1.stderr

  filename=$(basename "$gt_script")
  extension="${filename##*.}"

  if [ "$extension" == "bash" ]; then
    executor=bash
  elif [ "$extension" == "rb" ]; then
    # attempt to load RVM, just in case
    [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
    source $gt_dir/.rvmrc

    executor=ruby
  fi

  output=$($executor $gt_script 2> $error_log)

  if [ -n "$output" ]; then
    echo $output
  else
    echo \!\!\! - No output, check error log: $error_log
  fi

else
  echo "\!\!\! - File not found: $gt_script"
fi
