#!/usr/bin/env bash

# Exit with error if it doesn't recieve a script name on the commandline
if [ -z "$1" ]; then
  echo \!\!\! - No script name provided
  exit 255
fi

# Set up our directories, I suggest $HOME/.gt for this script and $HOME/.gt/scripts for the others
gt_dir=$HOME/.gt
script_dir=$gt_dir/scripts

function find_script { find . -name "$1.*" 2> /dev/null | head -1; }
script=$(find_script $1)

# If the script is found, then run it
if [ -e "$script" ]; then

  error_log=$gt_dir/logs/$1.stderr
  output=$(bash $script 2> $error_log)

  if [ -n "$output" ]; then
    echo $output
  else
    echo \!\!\! - No output, check error log: $error_log
  fi

else
  echo "\!\!\! - File not found: $script"
fi
